import { films } from '../Data/films.js'

console.log("Hi there! My first JavaScript Code!")

console.log(document.querySelector('.greeting'))

let greetingDiv = document.querySelector('.greeting')

greetingDiv.textContent = 'Welcome to my page! This mesage was generated by my JavaScript code!'